### ISSUE TITLE
Handling of curl options with spaces in them

### ISSUE THREAD

**Issue by stefanholzmueller** [shivkanthb/curlx#4]
I was trying curlx with the `-H` option I often use with curl: `cx "http://192.168.23.167" -H "Accept: application/json"`

This caused the following error message:
```
Command failed: curl -i "http://192.168.23.167" "-H" "Accept:" "application/json"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   143  100   143    0     0   2465      0 --:--:-- --:--:-- --:--:--  2465
curl: (6) Could not resolve host: application

(node:26295) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'responseHeaders' of null
    at module.exports (/usr/local/lib/node_modules/curlx/cmds/curlx.js:8:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:26295) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26295) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Somehow the header got separated into two command-line arguments: `"Accept:" "application/json"` which causes a subsequent error: `curl: (6) Could not resolve host: application`

The rest of the output seems to be an internal error.

I've tried a bit with single vs. double quotes, but could not get it working.

I'm using curlx v0.0.10 with zsh on Ubuntu, if it matters.

**Comment by shivkanthb** [comment]
Thanks for reporting this @stefanholzmueller! A new version 0.0.11 is pushed and it should work good now. Thanks to @apm963 for fixing it!

**Comment by stefanholzmueller** [comment]
I tried the new version and #2 seems to fix it. Thanks!
