### ISSUE TITLE
CLI command clash

### ISSUE THREAD

**Issue by TrevorHinesley** [shivkanthb/curlx#5]
Cloud 66 has a toolbelt (https://blog.cloud66.com/getting-started-with-cloud-66-toolbelt/) that I've been using for years as a part of different teams, and its CLI command is `cx` much like curlx. Is there an easy way to adjust the command to be a different string of characters?

**Comment by shivkanthb** [comment]
Does the conflict prevent curlx being installed too? If not, have you tried using `curlx`? It should work the same way as `cx`

**Comment by shivkanthb** [comment]
Closing this assuming the above fix works! Feel free to open it again if that's not the case.
