### ISSUE TITLE
curlx.dev website lists incorrect latest version

### ISSUE THREAD

**Issue by kashnoorani** [shivkanthb/curlx#7]
Says "Latest version is 1.0.0" when its actually 0.0.12.

<img width="639" alt="image" src="https://user-images.githubusercontent.com/2106211/61317514-f99a3f00-a7b7-11e9-832a-f00c4fef422d.png">

**Comment by shivkanthb** [comment]
Thanks for reporting this bug @kashnoorani. I updated the landing page to reflect the current version.
